spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clothify_crm
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

      jackson:
        serialization:
          fail-on-empty-beans: false


razorpay:
  api:
    key: rzp_test_F7R3zW5SMz3vVq
    secret: GCXjfbhQ2b1qPecwuOpy1Lox

